# Generated by Django 2.2.5 on 2019-12-11 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20191206_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register', to='profiles.Profile'),
        ),
    ]
