# Generated by Django 2.2.5 on 2019-09-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190930_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='houselhold_name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
