# Generated by Django 2.2.6 on 2019-10-07 09:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191001_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outing',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organized_outings', to='api.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accepted', models.DateField()),
                ('is_participant', models.BooleanField(blank=True, null=True)),
                ('is_driver', models.BooleanField(blank=True, null=True)),
                ('attendance_notes', models.CharField(blank=True, max_length=255)),
                ('outing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.Outing')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.Profile')),
            ],
            options={
                'unique_together': {('outing', 'profile')},
            },
        ),
        migrations.AddField(
            model_name='outing',
            name='attendees',
            field=models.ManyToManyField(related_name='attending_outings', through='api.Attendance', to='api.Profile'),
        ),
    ]
