# Generated by Django 2.2.6 on 2019-10-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191007_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_accepted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
