# Generated by Django 2.2.6 on 2019-10-07 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191007_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date_accepted',
        ),
        migrations.AddField(
            model_name='attendance',
            name='accepted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
