# Generated by Django 2.2.6 on 2019-11-05 09:46

import api.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=api.models.profile.scramble_uploaded_filename, verbose_name='Uploaded image'),
        ),
    ]
