# Generated by Django 2.2.6 on 2019-11-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191105_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing',
            name='location',
            field=models.CharField(default='angers', max_length=120),
            preserve_default=False,
        ),
    ]
