# Generated by Django 2.2.6 on 2019-11-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_outing_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
