# Generated by Django 2.2.5 on 2019-11-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_community'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'communities'},
        ),
        migrations.AddField(
            model_name='profile',
            name='icon_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='icon_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
