# Generated by Django 2.2.5 on 2019-12-06 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outings', '0001_initial'),
        ('profiles', '0001_initial'),
        ('communities', '0002_auto_20191206_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing',
            name='attendees',
            field=models.ManyToManyField(related_name='attending_outings', through='outings.Attendance', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='outing',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outings', to='communities.Community'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='outing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='outings.Outing'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='profiles.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('outing', 'profile')},
        ),
    ]
