# Generated by Django 2.2.5 on 2020-01-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_auto_20191211_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='deleted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
